{{ if .Values.sealed_secrets.enable }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infra

  destination:
    server: https://kubernetes.default.svc
    namespace: sealed-secrets

  source:
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    chart: sealed-secrets
    targetRevision: {{ .Values.sealed_secrets.targetRevision | default "main" }}

  syncPolicy:
    automated:
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default )
    syncOptions:
      - CreateNamespace=true
{{ end }}
